server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.93.6.66:3306/huiyike?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: Dl@huiyike123
    driver-class-name: com.mysql.cj.jdbc.Driver